//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillionBankInterface.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://BillionBanksWS.org", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfInt", Namespace="http://BillionBanksWS.org", ItemName="int")]
    [System.SerializableAttribute()]
    public class ArrayOfInt : System.Collections.Generic.List<int> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfDecimal", Namespace="http://BillionBanksWS.org", ItemName="decimal")]
    [System.SerializableAttribute()]
    public class ArrayOfDecimal : System.Collections.Generic.List<decimal> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://BillionBanksWS.org", ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name name from namespace http://BillionBanksWS.org is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://BillionBanksWS.org/AddUserDetails", ReplyAction="*")]
        BillionBankInterface.ServiceReference1.AddUserDetailsResponse AddUserDetails(BillionBankInterface.ServiceReference1.AddUserDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://BillionBanksWS.org/AddUserDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<BillionBankInterface.ServiceReference1.AddUserDetailsResponse> AddUserDetailsAsync(BillionBankInterface.ServiceReference1.AddUserDetailsRequest request);
        
        // CODEGEN: Generating message contract since element name email from namespace http://BillionBanksWS.org is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://BillionBanksWS.org/LogIn", ReplyAction="*")]
        BillionBankInterface.ServiceReference1.LogInResponse LogIn(BillionBankInterface.ServiceReference1.LogInRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://BillionBanksWS.org/LogIn", ReplyAction="*")]
        System.Threading.Tasks.Task<BillionBankInterface.ServiceReference1.LogInResponse> LogInAsync(BillionBankInterface.ServiceReference1.LogInRequest request);
        
        // CODEGEN: Generating message contract since element name email from namespace http://BillionBanksWS.org is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://BillionBanksWS.org/GetQuestion", ReplyAction="*")]
        BillionBankInterface.ServiceReference1.GetQuestionResponse GetQuestion(BillionBankInterface.ServiceReference1.GetQuestionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://BillionBanksWS.org/GetQuestion", ReplyAction="*")]
        System.Threading.Tasks.Task<BillionBankInterface.ServiceReference1.GetQuestionResponse> GetQuestionAsync(BillionBankInterface.ServiceReference1.GetQuestionRequest request);
        
        // CODEGEN: Generating message contract since element name answer from namespace http://BillionBanksWS.org is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://BillionBanksWS.org/CheckPassword", ReplyAction="*")]
        BillionBankInterface.ServiceReference1.CheckPasswordResponse CheckPassword(BillionBankInterface.ServiceReference1.CheckPasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://BillionBanksWS.org/CheckPassword", ReplyAction="*")]
        System.Threading.Tasks.Task<BillionBankInterface.ServiceReference1.CheckPasswordResponse> CheckPasswordAsync(BillionBankInterface.ServiceReference1.CheckPasswordRequest request);
        
        // CODEGEN: Generating message contract since element name sessionvar from namespace http://BillionBanksWS.org is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://BillionBanksWS.org/SetPassword", ReplyAction="*")]
        BillionBankInterface.ServiceReference1.SetPasswordResponse SetPassword(BillionBankInterface.ServiceReference1.SetPasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://BillionBanksWS.org/SetPassword", ReplyAction="*")]
        System.Threading.Tasks.Task<BillionBankInterface.ServiceReference1.SetPasswordResponse> SetPasswordAsync(BillionBankInterface.ServiceReference1.SetPasswordRequest request);
        
        // CODEGEN: Generating message contract since element name sessionvar from namespace http://BillionBanksWS.org is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://BillionBanksWS.org/CreateAccount", ReplyAction="*")]
        BillionBankInterface.ServiceReference1.CreateAccountResponse CreateAccount(BillionBankInterface.ServiceReference1.CreateAccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://BillionBanksWS.org/CreateAccount", ReplyAction="*")]
        System.Threading.Tasks.Task<BillionBankInterface.ServiceReference1.CreateAccountResponse> CreateAccountAsync(BillionBankInterface.ServiceReference1.CreateAccountRequest request);
        
        // CODEGEN: Generating message contract since element name sessionvar from namespace http://BillionBanksWS.org is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://BillionBanksWS.org/GetAccounts", ReplyAction="*")]
        BillionBankInterface.ServiceReference1.GetAccountsResponse GetAccounts(BillionBankInterface.ServiceReference1.GetAccountsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://BillionBanksWS.org/GetAccounts", ReplyAction="*")]
        System.Threading.Tasks.Task<BillionBankInterface.ServiceReference1.GetAccountsResponse> GetAccountsAsync(BillionBankInterface.ServiceReference1.GetAccountsRequest request);
        
        // CODEGEN: Generating message contract since element name sessionvar from namespace http://BillionBanksWS.org is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://BillionBanksWS.org/PopulateList", ReplyAction="*")]
        BillionBankInterface.ServiceReference1.PopulateListResponse PopulateList(BillionBankInterface.ServiceReference1.PopulateListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://BillionBanksWS.org/PopulateList", ReplyAction="*")]
        System.Threading.Tasks.Task<BillionBankInterface.ServiceReference1.PopulateListResponse> PopulateListAsync(BillionBankInterface.ServiceReference1.PopulateListRequest request);
        
        // CODEGEN: Generating message contract since element name sessionvar from namespace http://BillionBanksWS.org is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://BillionBanksWS.org/GetCurrentBalance", ReplyAction="*")]
        BillionBankInterface.ServiceReference1.GetCurrentBalanceResponse GetCurrentBalance(BillionBankInterface.ServiceReference1.GetCurrentBalanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://BillionBanksWS.org/GetCurrentBalance", ReplyAction="*")]
        System.Threading.Tasks.Task<BillionBankInterface.ServiceReference1.GetCurrentBalanceResponse> GetCurrentBalanceAsync(BillionBankInterface.ServiceReference1.GetCurrentBalanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://BillionBanksWS.org/TransferMoney", ReplyAction="*")]
        void TransferMoney(int destinationAcc, int sourceAccount, decimal amountToTransfer, decimal currentBalanceSource, decimal currentBalanceDest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://BillionBanksWS.org/TransferMoney", ReplyAction="*")]
        System.Threading.Tasks.Task TransferMoneyAsync(int destinationAcc, int sourceAccount, decimal amountToTransfer, decimal currentBalanceSource, decimal currentBalanceDest);
        
        // CODEGEN: Generating message contract since element name GetRecentTransactionResult from namespace http://BillionBanksWS.org is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://BillionBanksWS.org/GetRecentTransaction", ReplyAction="*")]
        BillionBankInterface.ServiceReference1.GetRecentTransactionResponse GetRecentTransaction(BillionBankInterface.ServiceReference1.GetRecentTransactionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://BillionBanksWS.org/GetRecentTransaction", ReplyAction="*")]
        System.Threading.Tasks.Task<BillionBankInterface.ServiceReference1.GetRecentTransactionResponse> GetRecentTransactionAsync(BillionBankInterface.ServiceReference1.GetRecentTransactionRequest request);
        
        // CODEGEN: Generating message contract since element name sessionvar from namespace http://BillionBanksWS.org is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://BillionBanksWS.org/UpdateDetails", ReplyAction="*")]
        BillionBankInterface.ServiceReference1.UpdateDetailsResponse UpdateDetails(BillionBankInterface.ServiceReference1.UpdateDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://BillionBanksWS.org/UpdateDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<BillionBankInterface.ServiceReference1.UpdateDetailsResponse> UpdateDetailsAsync(BillionBankInterface.ServiceReference1.UpdateDetailsRequest request);
        
        // CODEGEN: Generating message contract since element name logFileName from namespace http://BillionBanksWS.org is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://BillionBanksWS.org/WriteToLog", ReplyAction="*")]
        BillionBankInterface.ServiceReference1.WriteToLogResponse WriteToLog(BillionBankInterface.ServiceReference1.WriteToLogRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://BillionBanksWS.org/WriteToLog", ReplyAction="*")]
        System.Threading.Tasks.Task<BillionBankInterface.ServiceReference1.WriteToLogResponse> WriteToLogAsync(BillionBankInterface.ServiceReference1.WriteToLogRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddUserDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddUserDetails", Namespace="http://BillionBanksWS.org", Order=0)]
        public BillionBankInterface.ServiceReference1.AddUserDetailsRequestBody Body;
        
        public AddUserDetailsRequest() {
        }
        
        public AddUserDetailsRequest(BillionBankInterface.ServiceReference1.AddUserDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://BillionBanksWS.org")]
    public partial class AddUserDetailsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string surname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string contactNum;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string secQ;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string secA;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string physAdd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string pw;
        
        public AddUserDetailsRequestBody() {
        }
        
        public AddUserDetailsRequestBody(string name, string surname, string ID, string email, string contactNum, string secQ, string secA, string physAdd, string pw) {
            this.name = name;
            this.surname = surname;
            this.ID = ID;
            this.email = email;
            this.contactNum = contactNum;
            this.secQ = secQ;
            this.secA = secA;
            this.physAdd = physAdd;
            this.pw = pw;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddUserDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddUserDetailsResponse", Namespace="http://BillionBanksWS.org", Order=0)]
        public BillionBankInterface.ServiceReference1.AddUserDetailsResponseBody Body;
        
        public AddUserDetailsResponse() {
        }
        
        public AddUserDetailsResponse(BillionBankInterface.ServiceReference1.AddUserDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddUserDetailsResponseBody {
        
        public AddUserDetailsResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogInRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogIn", Namespace="http://BillionBanksWS.org", Order=0)]
        public BillionBankInterface.ServiceReference1.LogInRequestBody Body;
        
        public LogInRequest() {
        }
        
        public LogInRequest(BillionBankInterface.ServiceReference1.LogInRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://BillionBanksWS.org")]
    public partial class LogInRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public LogInRequestBody() {
        }
        
        public LogInRequestBody(string email, string password) {
            this.email = email;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogInResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogInResponse", Namespace="http://BillionBanksWS.org", Order=0)]
        public BillionBankInterface.ServiceReference1.LogInResponseBody Body;
        
        public LogInResponse() {
        }
        
        public LogInResponse(BillionBankInterface.ServiceReference1.LogInResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://BillionBanksWS.org")]
    public partial class LogInResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LogInResult;
        
        public LogInResponseBody() {
        }
        
        public LogInResponseBody(string LogInResult) {
            this.LogInResult = LogInResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetQuestionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetQuestion", Namespace="http://BillionBanksWS.org", Order=0)]
        public BillionBankInterface.ServiceReference1.GetQuestionRequestBody Body;
        
        public GetQuestionRequest() {
        }
        
        public GetQuestionRequest(BillionBankInterface.ServiceReference1.GetQuestionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://BillionBanksWS.org")]
    public partial class GetQuestionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        public GetQuestionRequestBody() {
        }
        
        public GetQuestionRequestBody(string email) {
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetQuestionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetQuestionResponse", Namespace="http://BillionBanksWS.org", Order=0)]
        public BillionBankInterface.ServiceReference1.GetQuestionResponseBody Body;
        
        public GetQuestionResponse() {
        }
        
        public GetQuestionResponse(BillionBankInterface.ServiceReference1.GetQuestionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://BillionBanksWS.org")]
    public partial class GetQuestionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BillionBankInterface.ServiceReference1.ArrayOfString GetQuestionResult;
        
        public GetQuestionResponseBody() {
        }
        
        public GetQuestionResponseBody(BillionBankInterface.ServiceReference1.ArrayOfString GetQuestionResult) {
            this.GetQuestionResult = GetQuestionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckPasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckPassword", Namespace="http://BillionBanksWS.org", Order=0)]
        public BillionBankInterface.ServiceReference1.CheckPasswordRequestBody Body;
        
        public CheckPasswordRequest() {
        }
        
        public CheckPasswordRequest(BillionBankInterface.ServiceReference1.CheckPasswordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://BillionBanksWS.org")]
    public partial class CheckPasswordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string answer;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string email;
        
        public CheckPasswordRequestBody() {
        }
        
        public CheckPasswordRequestBody(string answer, string email) {
            this.answer = answer;
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckPasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckPasswordResponse", Namespace="http://BillionBanksWS.org", Order=0)]
        public BillionBankInterface.ServiceReference1.CheckPasswordResponseBody Body;
        
        public CheckPasswordResponse() {
        }
        
        public CheckPasswordResponse(BillionBankInterface.ServiceReference1.CheckPasswordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://BillionBanksWS.org")]
    public partial class CheckPasswordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CheckPasswordResult;
        
        public CheckPasswordResponseBody() {
        }
        
        public CheckPasswordResponseBody(string CheckPasswordResult) {
            this.CheckPasswordResult = CheckPasswordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetPasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetPassword", Namespace="http://BillionBanksWS.org", Order=0)]
        public BillionBankInterface.ServiceReference1.SetPasswordRequestBody Body;
        
        public SetPasswordRequest() {
        }
        
        public SetPasswordRequest(BillionBankInterface.ServiceReference1.SetPasswordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://BillionBanksWS.org")]
    public partial class SetPasswordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionvar;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public SetPasswordRequestBody() {
        }
        
        public SetPasswordRequestBody(string sessionvar, string password) {
            this.sessionvar = sessionvar;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetPasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetPasswordResponse", Namespace="http://BillionBanksWS.org", Order=0)]
        public BillionBankInterface.ServiceReference1.SetPasswordResponseBody Body;
        
        public SetPasswordResponse() {
        }
        
        public SetPasswordResponse(BillionBankInterface.ServiceReference1.SetPasswordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SetPasswordResponseBody {
        
        public SetPasswordResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateAccountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateAccount", Namespace="http://BillionBanksWS.org", Order=0)]
        public BillionBankInterface.ServiceReference1.CreateAccountRequestBody Body;
        
        public CreateAccountRequest() {
        }
        
        public CreateAccountRequest(BillionBankInterface.ServiceReference1.CreateAccountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://BillionBanksWS.org")]
    public partial class CreateAccountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionvar;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string accountType;
        
        public CreateAccountRequestBody() {
        }
        
        public CreateAccountRequestBody(string sessionvar, string accountType) {
            this.sessionvar = sessionvar;
            this.accountType = accountType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateAccountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateAccountResponse", Namespace="http://BillionBanksWS.org", Order=0)]
        public BillionBankInterface.ServiceReference1.CreateAccountResponseBody Body;
        
        public CreateAccountResponse() {
        }
        
        public CreateAccountResponse(BillionBankInterface.ServiceReference1.CreateAccountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CreateAccountResponseBody {
        
        public CreateAccountResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAccountsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAccounts", Namespace="http://BillionBanksWS.org", Order=0)]
        public BillionBankInterface.ServiceReference1.GetAccountsRequestBody Body;
        
        public GetAccountsRequest() {
        }
        
        public GetAccountsRequest(BillionBankInterface.ServiceReference1.GetAccountsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://BillionBanksWS.org")]
    public partial class GetAccountsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionvar;
        
        public GetAccountsRequestBody() {
        }
        
        public GetAccountsRequestBody(string sessionvar) {
            this.sessionvar = sessionvar;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAccountsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAccountsResponse", Namespace="http://BillionBanksWS.org", Order=0)]
        public BillionBankInterface.ServiceReference1.GetAccountsResponseBody Body;
        
        public GetAccountsResponse() {
        }
        
        public GetAccountsResponse(BillionBankInterface.ServiceReference1.GetAccountsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://BillionBanksWS.org")]
    public partial class GetAccountsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BillionBankInterface.ServiceReference1.ArrayOfInt GetAccountsResult;
        
        public GetAccountsResponseBody() {
        }
        
        public GetAccountsResponseBody(BillionBankInterface.ServiceReference1.ArrayOfInt GetAccountsResult) {
            this.GetAccountsResult = GetAccountsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PopulateListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PopulateList", Namespace="http://BillionBanksWS.org", Order=0)]
        public BillionBankInterface.ServiceReference1.PopulateListRequestBody Body;
        
        public PopulateListRequest() {
        }
        
        public PopulateListRequest(BillionBankInterface.ServiceReference1.PopulateListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://BillionBanksWS.org")]
    public partial class PopulateListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionvar;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int accountNumber;
        
        public PopulateListRequestBody() {
        }
        
        public PopulateListRequestBody(string sessionvar, int accountNumber) {
            this.sessionvar = sessionvar;
            this.accountNumber = accountNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PopulateListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PopulateListResponse", Namespace="http://BillionBanksWS.org", Order=0)]
        public BillionBankInterface.ServiceReference1.PopulateListResponseBody Body;
        
        public PopulateListResponse() {
        }
        
        public PopulateListResponse(BillionBankInterface.ServiceReference1.PopulateListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://BillionBanksWS.org")]
    public partial class PopulateListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BillionBankInterface.ServiceReference1.ArrayOfString PopulateListResult;
        
        public PopulateListResponseBody() {
        }
        
        public PopulateListResponseBody(BillionBankInterface.ServiceReference1.ArrayOfString PopulateListResult) {
            this.PopulateListResult = PopulateListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrentBalanceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrentBalance", Namespace="http://BillionBanksWS.org", Order=0)]
        public BillionBankInterface.ServiceReference1.GetCurrentBalanceRequestBody Body;
        
        public GetCurrentBalanceRequest() {
        }
        
        public GetCurrentBalanceRequest(BillionBankInterface.ServiceReference1.GetCurrentBalanceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://BillionBanksWS.org")]
    public partial class GetCurrentBalanceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionvar;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int selectedAccount;
        
        public GetCurrentBalanceRequestBody() {
        }
        
        public GetCurrentBalanceRequestBody(string sessionvar, int selectedAccount) {
            this.sessionvar = sessionvar;
            this.selectedAccount = selectedAccount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrentBalanceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrentBalanceResponse", Namespace="http://BillionBanksWS.org", Order=0)]
        public BillionBankInterface.ServiceReference1.GetCurrentBalanceResponseBody Body;
        
        public GetCurrentBalanceResponse() {
        }
        
        public GetCurrentBalanceResponse(BillionBankInterface.ServiceReference1.GetCurrentBalanceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://BillionBanksWS.org")]
    public partial class GetCurrentBalanceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BillionBankInterface.ServiceReference1.ArrayOfDecimal GetCurrentBalanceResult;
        
        public GetCurrentBalanceResponseBody() {
        }
        
        public GetCurrentBalanceResponseBody(BillionBankInterface.ServiceReference1.ArrayOfDecimal GetCurrentBalanceResult) {
            this.GetCurrentBalanceResult = GetCurrentBalanceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRecentTransactionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRecentTransaction", Namespace="http://BillionBanksWS.org", Order=0)]
        public BillionBankInterface.ServiceReference1.GetRecentTransactionRequestBody Body;
        
        public GetRecentTransactionRequest() {
        }
        
        public GetRecentTransactionRequest(BillionBankInterface.ServiceReference1.GetRecentTransactionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://BillionBanksWS.org")]
    public partial class GetRecentTransactionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int accountNr;
        
        public GetRecentTransactionRequestBody() {
        }
        
        public GetRecentTransactionRequestBody(int accountNr) {
            this.accountNr = accountNr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRecentTransactionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRecentTransactionResponse", Namespace="http://BillionBanksWS.org", Order=0)]
        public BillionBankInterface.ServiceReference1.GetRecentTransactionResponseBody Body;
        
        public GetRecentTransactionResponse() {
        }
        
        public GetRecentTransactionResponse(BillionBankInterface.ServiceReference1.GetRecentTransactionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://BillionBanksWS.org")]
    public partial class GetRecentTransactionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BillionBankInterface.ServiceReference1.ArrayOfString GetRecentTransactionResult;
        
        public GetRecentTransactionResponseBody() {
        }
        
        public GetRecentTransactionResponseBody(BillionBankInterface.ServiceReference1.ArrayOfString GetRecentTransactionResult) {
            this.GetRecentTransactionResult = GetRecentTransactionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateDetails", Namespace="http://BillionBanksWS.org", Order=0)]
        public BillionBankInterface.ServiceReference1.UpdateDetailsRequestBody Body;
        
        public UpdateDetailsRequest() {
        }
        
        public UpdateDetailsRequest(BillionBankInterface.ServiceReference1.UpdateDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://BillionBanksWS.org")]
    public partial class UpdateDetailsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionvar;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string surname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string contactNum;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string secretQ;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string secretA;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string physAdd;
        
        public UpdateDetailsRequestBody() {
        }
        
        public UpdateDetailsRequestBody(string sessionvar, string name, string surname, string email, string contactNum, string secretQ, string secretA, string physAdd) {
            this.sessionvar = sessionvar;
            this.name = name;
            this.surname = surname;
            this.email = email;
            this.contactNum = contactNum;
            this.secretQ = secretQ;
            this.secretA = secretA;
            this.physAdd = physAdd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateDetailsResponse", Namespace="http://BillionBanksWS.org", Order=0)]
        public BillionBankInterface.ServiceReference1.UpdateDetailsResponseBody Body;
        
        public UpdateDetailsResponse() {
        }
        
        public UpdateDetailsResponse(BillionBankInterface.ServiceReference1.UpdateDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateDetailsResponseBody {
        
        public UpdateDetailsResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WriteToLogRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WriteToLog", Namespace="http://BillionBanksWS.org", Order=0)]
        public BillionBankInterface.ServiceReference1.WriteToLogRequestBody Body;
        
        public WriteToLogRequest() {
        }
        
        public WriteToLogRequest(BillionBankInterface.ServiceReference1.WriteToLogRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://BillionBanksWS.org")]
    public partial class WriteToLogRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int destinationAcc;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int sourceAccount;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public decimal amountToTransfer;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string logFileName;
        
        public WriteToLogRequestBody() {
        }
        
        public WriteToLogRequestBody(int destinationAcc, int sourceAccount, decimal amountToTransfer, string logFileName) {
            this.destinationAcc = destinationAcc;
            this.sourceAccount = sourceAccount;
            this.amountToTransfer = amountToTransfer;
            this.logFileName = logFileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WriteToLogResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WriteToLogResponse", Namespace="http://BillionBanksWS.org", Order=0)]
        public BillionBankInterface.ServiceReference1.WriteToLogResponseBody Body;
        
        public WriteToLogResponse() {
        }
        
        public WriteToLogResponse(BillionBankInterface.ServiceReference1.WriteToLogResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class WriteToLogResponseBody {
        
        public WriteToLogResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : BillionBankInterface.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<BillionBankInterface.ServiceReference1.WebService1Soap>, BillionBankInterface.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BillionBankInterface.ServiceReference1.AddUserDetailsResponse BillionBankInterface.ServiceReference1.WebService1Soap.AddUserDetails(BillionBankInterface.ServiceReference1.AddUserDetailsRequest request) {
            return base.Channel.AddUserDetails(request);
        }
        
        public void AddUserDetails(string name, string surname, string ID, string email, string contactNum, string secQ, string secA, string physAdd, string pw) {
            BillionBankInterface.ServiceReference1.AddUserDetailsRequest inValue = new BillionBankInterface.ServiceReference1.AddUserDetailsRequest();
            inValue.Body = new BillionBankInterface.ServiceReference1.AddUserDetailsRequestBody();
            inValue.Body.name = name;
            inValue.Body.surname = surname;
            inValue.Body.ID = ID;
            inValue.Body.email = email;
            inValue.Body.contactNum = contactNum;
            inValue.Body.secQ = secQ;
            inValue.Body.secA = secA;
            inValue.Body.physAdd = physAdd;
            inValue.Body.pw = pw;
            BillionBankInterface.ServiceReference1.AddUserDetailsResponse retVal = ((BillionBankInterface.ServiceReference1.WebService1Soap)(this)).AddUserDetails(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BillionBankInterface.ServiceReference1.AddUserDetailsResponse> BillionBankInterface.ServiceReference1.WebService1Soap.AddUserDetailsAsync(BillionBankInterface.ServiceReference1.AddUserDetailsRequest request) {
            return base.Channel.AddUserDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<BillionBankInterface.ServiceReference1.AddUserDetailsResponse> AddUserDetailsAsync(string name, string surname, string ID, string email, string contactNum, string secQ, string secA, string physAdd, string pw) {
            BillionBankInterface.ServiceReference1.AddUserDetailsRequest inValue = new BillionBankInterface.ServiceReference1.AddUserDetailsRequest();
            inValue.Body = new BillionBankInterface.ServiceReference1.AddUserDetailsRequestBody();
            inValue.Body.name = name;
            inValue.Body.surname = surname;
            inValue.Body.ID = ID;
            inValue.Body.email = email;
            inValue.Body.contactNum = contactNum;
            inValue.Body.secQ = secQ;
            inValue.Body.secA = secA;
            inValue.Body.physAdd = physAdd;
            inValue.Body.pw = pw;
            return ((BillionBankInterface.ServiceReference1.WebService1Soap)(this)).AddUserDetailsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BillionBankInterface.ServiceReference1.LogInResponse BillionBankInterface.ServiceReference1.WebService1Soap.LogIn(BillionBankInterface.ServiceReference1.LogInRequest request) {
            return base.Channel.LogIn(request);
        }
        
        public string LogIn(string email, string password) {
            BillionBankInterface.ServiceReference1.LogInRequest inValue = new BillionBankInterface.ServiceReference1.LogInRequest();
            inValue.Body = new BillionBankInterface.ServiceReference1.LogInRequestBody();
            inValue.Body.email = email;
            inValue.Body.password = password;
            BillionBankInterface.ServiceReference1.LogInResponse retVal = ((BillionBankInterface.ServiceReference1.WebService1Soap)(this)).LogIn(inValue);
            return retVal.Body.LogInResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BillionBankInterface.ServiceReference1.LogInResponse> BillionBankInterface.ServiceReference1.WebService1Soap.LogInAsync(BillionBankInterface.ServiceReference1.LogInRequest request) {
            return base.Channel.LogInAsync(request);
        }
        
        public System.Threading.Tasks.Task<BillionBankInterface.ServiceReference1.LogInResponse> LogInAsync(string email, string password) {
            BillionBankInterface.ServiceReference1.LogInRequest inValue = new BillionBankInterface.ServiceReference1.LogInRequest();
            inValue.Body = new BillionBankInterface.ServiceReference1.LogInRequestBody();
            inValue.Body.email = email;
            inValue.Body.password = password;
            return ((BillionBankInterface.ServiceReference1.WebService1Soap)(this)).LogInAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BillionBankInterface.ServiceReference1.GetQuestionResponse BillionBankInterface.ServiceReference1.WebService1Soap.GetQuestion(BillionBankInterface.ServiceReference1.GetQuestionRequest request) {
            return base.Channel.GetQuestion(request);
        }
        
        public BillionBankInterface.ServiceReference1.ArrayOfString GetQuestion(string email) {
            BillionBankInterface.ServiceReference1.GetQuestionRequest inValue = new BillionBankInterface.ServiceReference1.GetQuestionRequest();
            inValue.Body = new BillionBankInterface.ServiceReference1.GetQuestionRequestBody();
            inValue.Body.email = email;
            BillionBankInterface.ServiceReference1.GetQuestionResponse retVal = ((BillionBankInterface.ServiceReference1.WebService1Soap)(this)).GetQuestion(inValue);
            return retVal.Body.GetQuestionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BillionBankInterface.ServiceReference1.GetQuestionResponse> BillionBankInterface.ServiceReference1.WebService1Soap.GetQuestionAsync(BillionBankInterface.ServiceReference1.GetQuestionRequest request) {
            return base.Channel.GetQuestionAsync(request);
        }
        
        public System.Threading.Tasks.Task<BillionBankInterface.ServiceReference1.GetQuestionResponse> GetQuestionAsync(string email) {
            BillionBankInterface.ServiceReference1.GetQuestionRequest inValue = new BillionBankInterface.ServiceReference1.GetQuestionRequest();
            inValue.Body = new BillionBankInterface.ServiceReference1.GetQuestionRequestBody();
            inValue.Body.email = email;
            return ((BillionBankInterface.ServiceReference1.WebService1Soap)(this)).GetQuestionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BillionBankInterface.ServiceReference1.CheckPasswordResponse BillionBankInterface.ServiceReference1.WebService1Soap.CheckPassword(BillionBankInterface.ServiceReference1.CheckPasswordRequest request) {
            return base.Channel.CheckPassword(request);
        }
        
        public string CheckPassword(string answer, string email) {
            BillionBankInterface.ServiceReference1.CheckPasswordRequest inValue = new BillionBankInterface.ServiceReference1.CheckPasswordRequest();
            inValue.Body = new BillionBankInterface.ServiceReference1.CheckPasswordRequestBody();
            inValue.Body.answer = answer;
            inValue.Body.email = email;
            BillionBankInterface.ServiceReference1.CheckPasswordResponse retVal = ((BillionBankInterface.ServiceReference1.WebService1Soap)(this)).CheckPassword(inValue);
            return retVal.Body.CheckPasswordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BillionBankInterface.ServiceReference1.CheckPasswordResponse> BillionBankInterface.ServiceReference1.WebService1Soap.CheckPasswordAsync(BillionBankInterface.ServiceReference1.CheckPasswordRequest request) {
            return base.Channel.CheckPasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<BillionBankInterface.ServiceReference1.CheckPasswordResponse> CheckPasswordAsync(string answer, string email) {
            BillionBankInterface.ServiceReference1.CheckPasswordRequest inValue = new BillionBankInterface.ServiceReference1.CheckPasswordRequest();
            inValue.Body = new BillionBankInterface.ServiceReference1.CheckPasswordRequestBody();
            inValue.Body.answer = answer;
            inValue.Body.email = email;
            return ((BillionBankInterface.ServiceReference1.WebService1Soap)(this)).CheckPasswordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BillionBankInterface.ServiceReference1.SetPasswordResponse BillionBankInterface.ServiceReference1.WebService1Soap.SetPassword(BillionBankInterface.ServiceReference1.SetPasswordRequest request) {
            return base.Channel.SetPassword(request);
        }
        
        public void SetPassword(string sessionvar, string password) {
            BillionBankInterface.ServiceReference1.SetPasswordRequest inValue = new BillionBankInterface.ServiceReference1.SetPasswordRequest();
            inValue.Body = new BillionBankInterface.ServiceReference1.SetPasswordRequestBody();
            inValue.Body.sessionvar = sessionvar;
            inValue.Body.password = password;
            BillionBankInterface.ServiceReference1.SetPasswordResponse retVal = ((BillionBankInterface.ServiceReference1.WebService1Soap)(this)).SetPassword(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BillionBankInterface.ServiceReference1.SetPasswordResponse> BillionBankInterface.ServiceReference1.WebService1Soap.SetPasswordAsync(BillionBankInterface.ServiceReference1.SetPasswordRequest request) {
            return base.Channel.SetPasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<BillionBankInterface.ServiceReference1.SetPasswordResponse> SetPasswordAsync(string sessionvar, string password) {
            BillionBankInterface.ServiceReference1.SetPasswordRequest inValue = new BillionBankInterface.ServiceReference1.SetPasswordRequest();
            inValue.Body = new BillionBankInterface.ServiceReference1.SetPasswordRequestBody();
            inValue.Body.sessionvar = sessionvar;
            inValue.Body.password = password;
            return ((BillionBankInterface.ServiceReference1.WebService1Soap)(this)).SetPasswordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BillionBankInterface.ServiceReference1.CreateAccountResponse BillionBankInterface.ServiceReference1.WebService1Soap.CreateAccount(BillionBankInterface.ServiceReference1.CreateAccountRequest request) {
            return base.Channel.CreateAccount(request);
        }
        
        public void CreateAccount(string sessionvar, string accountType) {
            BillionBankInterface.ServiceReference1.CreateAccountRequest inValue = new BillionBankInterface.ServiceReference1.CreateAccountRequest();
            inValue.Body = new BillionBankInterface.ServiceReference1.CreateAccountRequestBody();
            inValue.Body.sessionvar = sessionvar;
            inValue.Body.accountType = accountType;
            BillionBankInterface.ServiceReference1.CreateAccountResponse retVal = ((BillionBankInterface.ServiceReference1.WebService1Soap)(this)).CreateAccount(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BillionBankInterface.ServiceReference1.CreateAccountResponse> BillionBankInterface.ServiceReference1.WebService1Soap.CreateAccountAsync(BillionBankInterface.ServiceReference1.CreateAccountRequest request) {
            return base.Channel.CreateAccountAsync(request);
        }
        
        public System.Threading.Tasks.Task<BillionBankInterface.ServiceReference1.CreateAccountResponse> CreateAccountAsync(string sessionvar, string accountType) {
            BillionBankInterface.ServiceReference1.CreateAccountRequest inValue = new BillionBankInterface.ServiceReference1.CreateAccountRequest();
            inValue.Body = new BillionBankInterface.ServiceReference1.CreateAccountRequestBody();
            inValue.Body.sessionvar = sessionvar;
            inValue.Body.accountType = accountType;
            return ((BillionBankInterface.ServiceReference1.WebService1Soap)(this)).CreateAccountAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BillionBankInterface.ServiceReference1.GetAccountsResponse BillionBankInterface.ServiceReference1.WebService1Soap.GetAccounts(BillionBankInterface.ServiceReference1.GetAccountsRequest request) {
            return base.Channel.GetAccounts(request);
        }
        
        public BillionBankInterface.ServiceReference1.ArrayOfInt GetAccounts(string sessionvar) {
            BillionBankInterface.ServiceReference1.GetAccountsRequest inValue = new BillionBankInterface.ServiceReference1.GetAccountsRequest();
            inValue.Body = new BillionBankInterface.ServiceReference1.GetAccountsRequestBody();
            inValue.Body.sessionvar = sessionvar;
            BillionBankInterface.ServiceReference1.GetAccountsResponse retVal = ((BillionBankInterface.ServiceReference1.WebService1Soap)(this)).GetAccounts(inValue);
            return retVal.Body.GetAccountsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BillionBankInterface.ServiceReference1.GetAccountsResponse> BillionBankInterface.ServiceReference1.WebService1Soap.GetAccountsAsync(BillionBankInterface.ServiceReference1.GetAccountsRequest request) {
            return base.Channel.GetAccountsAsync(request);
        }
        
        public System.Threading.Tasks.Task<BillionBankInterface.ServiceReference1.GetAccountsResponse> GetAccountsAsync(string sessionvar) {
            BillionBankInterface.ServiceReference1.GetAccountsRequest inValue = new BillionBankInterface.ServiceReference1.GetAccountsRequest();
            inValue.Body = new BillionBankInterface.ServiceReference1.GetAccountsRequestBody();
            inValue.Body.sessionvar = sessionvar;
            return ((BillionBankInterface.ServiceReference1.WebService1Soap)(this)).GetAccountsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BillionBankInterface.ServiceReference1.PopulateListResponse BillionBankInterface.ServiceReference1.WebService1Soap.PopulateList(BillionBankInterface.ServiceReference1.PopulateListRequest request) {
            return base.Channel.PopulateList(request);
        }
        
        public BillionBankInterface.ServiceReference1.ArrayOfString PopulateList(string sessionvar, int accountNumber) {
            BillionBankInterface.ServiceReference1.PopulateListRequest inValue = new BillionBankInterface.ServiceReference1.PopulateListRequest();
            inValue.Body = new BillionBankInterface.ServiceReference1.PopulateListRequestBody();
            inValue.Body.sessionvar = sessionvar;
            inValue.Body.accountNumber = accountNumber;
            BillionBankInterface.ServiceReference1.PopulateListResponse retVal = ((BillionBankInterface.ServiceReference1.WebService1Soap)(this)).PopulateList(inValue);
            return retVal.Body.PopulateListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BillionBankInterface.ServiceReference1.PopulateListResponse> BillionBankInterface.ServiceReference1.WebService1Soap.PopulateListAsync(BillionBankInterface.ServiceReference1.PopulateListRequest request) {
            return base.Channel.PopulateListAsync(request);
        }
        
        public System.Threading.Tasks.Task<BillionBankInterface.ServiceReference1.PopulateListResponse> PopulateListAsync(string sessionvar, int accountNumber) {
            BillionBankInterface.ServiceReference1.PopulateListRequest inValue = new BillionBankInterface.ServiceReference1.PopulateListRequest();
            inValue.Body = new BillionBankInterface.ServiceReference1.PopulateListRequestBody();
            inValue.Body.sessionvar = sessionvar;
            inValue.Body.accountNumber = accountNumber;
            return ((BillionBankInterface.ServiceReference1.WebService1Soap)(this)).PopulateListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BillionBankInterface.ServiceReference1.GetCurrentBalanceResponse BillionBankInterface.ServiceReference1.WebService1Soap.GetCurrentBalance(BillionBankInterface.ServiceReference1.GetCurrentBalanceRequest request) {
            return base.Channel.GetCurrentBalance(request);
        }
        
        public BillionBankInterface.ServiceReference1.ArrayOfDecimal GetCurrentBalance(string sessionvar, int selectedAccount) {
            BillionBankInterface.ServiceReference1.GetCurrentBalanceRequest inValue = new BillionBankInterface.ServiceReference1.GetCurrentBalanceRequest();
            inValue.Body = new BillionBankInterface.ServiceReference1.GetCurrentBalanceRequestBody();
            inValue.Body.sessionvar = sessionvar;
            inValue.Body.selectedAccount = selectedAccount;
            BillionBankInterface.ServiceReference1.GetCurrentBalanceResponse retVal = ((BillionBankInterface.ServiceReference1.WebService1Soap)(this)).GetCurrentBalance(inValue);
            return retVal.Body.GetCurrentBalanceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BillionBankInterface.ServiceReference1.GetCurrentBalanceResponse> BillionBankInterface.ServiceReference1.WebService1Soap.GetCurrentBalanceAsync(BillionBankInterface.ServiceReference1.GetCurrentBalanceRequest request) {
            return base.Channel.GetCurrentBalanceAsync(request);
        }
        
        public System.Threading.Tasks.Task<BillionBankInterface.ServiceReference1.GetCurrentBalanceResponse> GetCurrentBalanceAsync(string sessionvar, int selectedAccount) {
            BillionBankInterface.ServiceReference1.GetCurrentBalanceRequest inValue = new BillionBankInterface.ServiceReference1.GetCurrentBalanceRequest();
            inValue.Body = new BillionBankInterface.ServiceReference1.GetCurrentBalanceRequestBody();
            inValue.Body.sessionvar = sessionvar;
            inValue.Body.selectedAccount = selectedAccount;
            return ((BillionBankInterface.ServiceReference1.WebService1Soap)(this)).GetCurrentBalanceAsync(inValue);
        }
        
        public void TransferMoney(int destinationAcc, int sourceAccount, decimal amountToTransfer, decimal currentBalanceSource, decimal currentBalanceDest) {
            base.Channel.TransferMoney(destinationAcc, sourceAccount, amountToTransfer, currentBalanceSource, currentBalanceDest);
        }
        
        public System.Threading.Tasks.Task TransferMoneyAsync(int destinationAcc, int sourceAccount, decimal amountToTransfer, decimal currentBalanceSource, decimal currentBalanceDest) {
            return base.Channel.TransferMoneyAsync(destinationAcc, sourceAccount, amountToTransfer, currentBalanceSource, currentBalanceDest);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BillionBankInterface.ServiceReference1.GetRecentTransactionResponse BillionBankInterface.ServiceReference1.WebService1Soap.GetRecentTransaction(BillionBankInterface.ServiceReference1.GetRecentTransactionRequest request) {
            return base.Channel.GetRecentTransaction(request);
        }
        
        public BillionBankInterface.ServiceReference1.ArrayOfString GetRecentTransaction(int accountNr) {
            BillionBankInterface.ServiceReference1.GetRecentTransactionRequest inValue = new BillionBankInterface.ServiceReference1.GetRecentTransactionRequest();
            inValue.Body = new BillionBankInterface.ServiceReference1.GetRecentTransactionRequestBody();
            inValue.Body.accountNr = accountNr;
            BillionBankInterface.ServiceReference1.GetRecentTransactionResponse retVal = ((BillionBankInterface.ServiceReference1.WebService1Soap)(this)).GetRecentTransaction(inValue);
            return retVal.Body.GetRecentTransactionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BillionBankInterface.ServiceReference1.GetRecentTransactionResponse> BillionBankInterface.ServiceReference1.WebService1Soap.GetRecentTransactionAsync(BillionBankInterface.ServiceReference1.GetRecentTransactionRequest request) {
            return base.Channel.GetRecentTransactionAsync(request);
        }
        
        public System.Threading.Tasks.Task<BillionBankInterface.ServiceReference1.GetRecentTransactionResponse> GetRecentTransactionAsync(int accountNr) {
            BillionBankInterface.ServiceReference1.GetRecentTransactionRequest inValue = new BillionBankInterface.ServiceReference1.GetRecentTransactionRequest();
            inValue.Body = new BillionBankInterface.ServiceReference1.GetRecentTransactionRequestBody();
            inValue.Body.accountNr = accountNr;
            return ((BillionBankInterface.ServiceReference1.WebService1Soap)(this)).GetRecentTransactionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BillionBankInterface.ServiceReference1.UpdateDetailsResponse BillionBankInterface.ServiceReference1.WebService1Soap.UpdateDetails(BillionBankInterface.ServiceReference1.UpdateDetailsRequest request) {
            return base.Channel.UpdateDetails(request);
        }
        
        public void UpdateDetails(string sessionvar, string name, string surname, string email, string contactNum, string secretQ, string secretA, string physAdd) {
            BillionBankInterface.ServiceReference1.UpdateDetailsRequest inValue = new BillionBankInterface.ServiceReference1.UpdateDetailsRequest();
            inValue.Body = new BillionBankInterface.ServiceReference1.UpdateDetailsRequestBody();
            inValue.Body.sessionvar = sessionvar;
            inValue.Body.name = name;
            inValue.Body.surname = surname;
            inValue.Body.email = email;
            inValue.Body.contactNum = contactNum;
            inValue.Body.secretQ = secretQ;
            inValue.Body.secretA = secretA;
            inValue.Body.physAdd = physAdd;
            BillionBankInterface.ServiceReference1.UpdateDetailsResponse retVal = ((BillionBankInterface.ServiceReference1.WebService1Soap)(this)).UpdateDetails(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BillionBankInterface.ServiceReference1.UpdateDetailsResponse> BillionBankInterface.ServiceReference1.WebService1Soap.UpdateDetailsAsync(BillionBankInterface.ServiceReference1.UpdateDetailsRequest request) {
            return base.Channel.UpdateDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<BillionBankInterface.ServiceReference1.UpdateDetailsResponse> UpdateDetailsAsync(string sessionvar, string name, string surname, string email, string contactNum, string secretQ, string secretA, string physAdd) {
            BillionBankInterface.ServiceReference1.UpdateDetailsRequest inValue = new BillionBankInterface.ServiceReference1.UpdateDetailsRequest();
            inValue.Body = new BillionBankInterface.ServiceReference1.UpdateDetailsRequestBody();
            inValue.Body.sessionvar = sessionvar;
            inValue.Body.name = name;
            inValue.Body.surname = surname;
            inValue.Body.email = email;
            inValue.Body.contactNum = contactNum;
            inValue.Body.secretQ = secretQ;
            inValue.Body.secretA = secretA;
            inValue.Body.physAdd = physAdd;
            return ((BillionBankInterface.ServiceReference1.WebService1Soap)(this)).UpdateDetailsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BillionBankInterface.ServiceReference1.WriteToLogResponse BillionBankInterface.ServiceReference1.WebService1Soap.WriteToLog(BillionBankInterface.ServiceReference1.WriteToLogRequest request) {
            return base.Channel.WriteToLog(request);
        }
        
        public void WriteToLog(int destinationAcc, int sourceAccount, decimal amountToTransfer, string logFileName) {
            BillionBankInterface.ServiceReference1.WriteToLogRequest inValue = new BillionBankInterface.ServiceReference1.WriteToLogRequest();
            inValue.Body = new BillionBankInterface.ServiceReference1.WriteToLogRequestBody();
            inValue.Body.destinationAcc = destinationAcc;
            inValue.Body.sourceAccount = sourceAccount;
            inValue.Body.amountToTransfer = amountToTransfer;
            inValue.Body.logFileName = logFileName;
            BillionBankInterface.ServiceReference1.WriteToLogResponse retVal = ((BillionBankInterface.ServiceReference1.WebService1Soap)(this)).WriteToLog(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BillionBankInterface.ServiceReference1.WriteToLogResponse> BillionBankInterface.ServiceReference1.WebService1Soap.WriteToLogAsync(BillionBankInterface.ServiceReference1.WriteToLogRequest request) {
            return base.Channel.WriteToLogAsync(request);
        }
        
        public System.Threading.Tasks.Task<BillionBankInterface.ServiceReference1.WriteToLogResponse> WriteToLogAsync(int destinationAcc, int sourceAccount, decimal amountToTransfer, string logFileName) {
            BillionBankInterface.ServiceReference1.WriteToLogRequest inValue = new BillionBankInterface.ServiceReference1.WriteToLogRequest();
            inValue.Body = new BillionBankInterface.ServiceReference1.WriteToLogRequestBody();
            inValue.Body.destinationAcc = destinationAcc;
            inValue.Body.sourceAccount = sourceAccount;
            inValue.Body.amountToTransfer = amountToTransfer;
            inValue.Body.logFileName = logFileName;
            return ((BillionBankInterface.ServiceReference1.WebService1Soap)(this)).WriteToLogAsync(inValue);
        }
    }
}
